// <auto-generated />
using MVC_MovieArchive.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVC_MovieArchive.Migrations
{
    [DbContext(typeof(MovieArchiveDbContext))]
    [Migration("20260926133646_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVC_MovieArchive.Models.Entities.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Director = "Çağan Irmak",
                            ReleaseYear = 2005,
                            Title = "Babam ve Oğlum"
                        },
                        new
                        {
                            Id = 2,
                            Director = "Nuri Bilge Ceylan",
                            ReleaseYear = 2018,
                            Title = "Ahlat Ağacı"
                        },
                        new
                        {
                            Id = 3,
                            Director = "Yavuz Turgul",
                            ReleaseYear = 1996,
                            Title = "Eşkıya"
                        },
                        new
                        {
                            Id = 4,
                            Director = "Ömer Faruk Sorak",
                            ReleaseYear = 2004,
                            Title = "G.O.R.A."
                        },
                        new
                        {
                            Id = 5,
                            Director = "Nuri Bilge Ceylan",
                            ReleaseYear = 2014,
                            Title = "Kış Uykusu"
                        },
                        new
                        {
                            Id = 6,
                            Director = "Yılmaz Erdoğan",
                            ReleaseYear = 2001,
                            Title = "Vizontele"
                        },
                        new
                        {
                            Id = 7,
                            Director = "Yılmaz Erdoğan",
                            ReleaseYear = 2005,
                            Title = "Organize İşler"
                        },
                        new
                        {
                            Id = 8,
                            Director = "Yılmaz Erdoğan",
                            ReleaseYear = 2009,
                            Title = "Neşeli Hayat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
