// <auto-generated />
using MVC_VetClinic.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVC_VetClinic.Migrations
{
    [DbContext(typeof(VetClinicDbContext))]
    partial class VetClinicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVC_VetClinic.Models.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 3,
                            Name = "Pamuk",
                            Species = "Kedi"
                        },
                        new
                        {
                            Id = 2,
                            Age = 5,
                            Name = "Karabaş",
                            Species = "Köpek"
                        },
                        new
                        {
                            Id = 3,
                            Age = 2,
                            Name = "Boncuk",
                            Species = "Tavşan"
                        },
                        new
                        {
                            Id = 4,
                            Age = 1,
                            Name = "Maviş",
                            Species = "Muhabbet Kuşu"
                        },
                        new
                        {
                            Id = 5,
                            Age = 4,
                            Name = "Duman",
                            Species = "Kedi"
                        },
                        new
                        {
                            Id = 6,
                            Age = 2,
                            Name = "Fındık",
                            Species = "Hamster"
                        },
                        new
                        {
                            Id = 7,
                            Age = 7,
                            Name = "Çakıl",
                            Species = "Kaplumbağa"
                        },
                        new
                        {
                            Id = 8,
                            Age = 3,
                            Name = "Limon",
                            Species = "Papağan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
