// <auto-generated />
using MVC_CafeMenu.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVC_CafeMenu.Migrations
{
    [DbContext(typeof(CafeMenuDbContext))]
    partial class CafeMenuDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVC_CafeMenu.Models.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Sıcak İçecek",
                            Name = "Türk Kahvesi",
                            Price = 90
                        },
                        new
                        {
                            Id = 2,
                            Category = "Sıcak İçecek",
                            Name = "Latte",
                            Price = 120
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sıcak İçecek",
                            Name = "Çay",
                            Price = 40
                        },
                        new
                        {
                            Id = 4,
                            Category = "Soğuk İçecek",
                            Name = "Limonata",
                            Price = 80
                        },
                        new
                        {
                            Id = 5,
                            Category = "Soğuk İçecek",
                            Name = "Soğuk Kahve",
                            Price = 110
                        },
                        new
                        {
                            Id = 6,
                            Category = "Tatlı",
                            Name = "Cheesecake",
                            Price = 150
                        },
                        new
                        {
                            Id = 7,
                            Category = "Tatlı",
                            Name = "Brownie",
                            Price = 130
                        },
                        new
                        {
                            Id = 8,
                            Category = "Hamur İşi",
                            Name = "Kruvasan",
                            Price = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
