// <auto-generated />
using MVC_GymMembers.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVC_GymMembers.Migrations
{
    [DbContext(typeof(GymMembersDbContext))]
    [Migration("20260926174215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVC_GymMembers.Models.Entities.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("MembershipType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 28,
                            FullName = "Ahmet Yıldız",
                            MembershipType = "Yıllık"
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            FullName = "Elif Kaya",
                            MembershipType = "Aylık"
                        },
                        new
                        {
                            Id = 3,
                            Age = 32,
                            FullName = "Mehmet Demir",
                            MembershipType = "3 Aylık"
                        },
                        new
                        {
                            Id = 4,
                            Age = 27,
                            FullName = "Zeynep Çelik",
                            MembershipType = "Yıllık"
                        },
                        new
                        {
                            Id = 5,
                            Age = 35,
                            FullName = "Can Arslan",
                            MembershipType = "Aylık"
                        },
                        new
                        {
                            Id = 6,
                            Age = 22,
                            FullName = "Naz Şahin",
                            MembershipType = "3 Aylık"
                        },
                        new
                        {
                            Id = 7,
                            Age = 30,
                            FullName = "Burak Fındık",
                            MembershipType = "Yıllık"
                        },
                        new
                        {
                            Id = 8,
                            Age = 26,
                            FullName = "Seda Tuna",
                            MembershipType = "Aylık"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
