// <auto-generated />
using MVC_TravelGuide.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MVC_TravelGuide.Migrations
{
    [DbContext(typeof(TravelGuideDbContext))]
    partial class TravelGuideDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MVC_TravelGuide.Models.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntryFee")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "İstanbul",
                            EntryFee = 1400,
                            Name = "Topkapı Sarayı"
                        },
                        new
                        {
                            Id = 2,
                            City = "İstanbul",
                            EntryFee = 0,
                            Name = "Ayasofya"
                        },
                        new
                        {
                            Id = 3,
                            City = "Ankara",
                            EntryFee = 0,
                            Name = "Anıtkabir"
                        },
                        new
                        {
                            Id = 4,
                            City = "Denizli",
                            EntryFee = 125,
                            Name = "Pamukkale Travertenleri"
                        },
                        new
                        {
                            Id = 5,
                            City = "İzmir",
                            EntryFee = 700,
                            Name = "Efes Antik Kenti"
                        },
                        new
                        {
                            Id = 6,
                            City = "Nevşehir",
                            EntryFee = 750,
                            Name = "Göreme Açık Hava Müzesi"
                        },
                        new
                        {
                            Id = 7,
                            City = "Trabzon",
                            EntryFee = 0,
                            Name = "Sümela Manastırı"
                        },
                        new
                        {
                            Id = 8,
                            City = "İstanbul",
                            EntryFee = 1000,
                            Name = "Galata Kulesi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
