services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cafe_user
      POSTGRES_PASSWORD: cafe_password
      POSTGRES_DB: cafe_db
    ports:
      - "12500:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: