services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: vet_user
      POSTGRES_PASSWORD: vet_password
      POSTGRES_DB: vet_db
    ports:
      - "12300:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: